apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aiven-sql
spec:
  crossplane:
    version: ">=v1.0.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-terraform
      version: ">=v0.10.0"
